---
kind: pipeline
type: kubernetes
name: "Release Docker Image"

trigger:
  branch:
    - main

platform:
  os: linux
  arch: arm64

steps:
  
  - name: publish
    image: plugins/docker:20.13
    pull: if-not-exists
    settings:
      auto_tag: false
      auto_tag_suffix: linux-arm64
      tags: "latest" 
      dockerfile: Dockerfile
      insecure: true
      username:
        from_secret: image_registry_user
      password:
        from_secret: image_registry_password
      registry:
        from_secret: image_registry
      repo:
        from_secret: destination_image

## IMPORTANT - update this when deploying new 
host_aliases:
  - ip: 10.43.99.186
    hostnames:
      - "gitea-127.0.0.1.sslip.io"