---
kind: pipeline
type: kubernetes
name: default

# update this if you want to do arm64 build
platform:
  os: linux
  arch: amd64

# Trigger only main
trigger:
  branch:
  - instruqt

steps:
  
  - name: publish
    image: plugins/docker:20.13
    pull: if-not-exists
    settings:
      tags: "latest" 
      dockerfile: docker/Dockerfile.linux.arm64
      insecure: true
      mtu: 1410
      build_args: 
        - "MAVEN_REPOS=nexus=http://nexus.infra:8081/repository/maven-public/"
      username:
        from_secret: image_registry_user
      password:
        from_secret: image_registry_password
      registry:
        from_secret: image_registry
      repo:
        from_secret: destination_image
