---
kind: pipeline
type: kubernetes
name: default

# remove this section if your CPU is amd64
platform:
  os: linux
  arch: arm64

# Trigger only main
trigger:
  branch:
  - main

steps:
  
  - name: publish
    image: plugins/docker:20.13
    pull: if-not-exists
    settings:
      tags: "latest" 
      dockerfile: docker/Dockerfile.linux.arm64
      insecure: true
      mtu: 1410
      build_args: 
        - "MAVEN_REPOS=nexus=http://nexus.infra:8081/repository/maven-public/"
      username:
        from_secret: image_registry_user
      password:
        from_secret: image_registry_password
      registry:
        from_secret: image_registry
      repo:
        from_secret: destination_image

# Ensuring the local gitea is reachable
host_aliases:
   # IMPORTANT: update to match your settings
   # export GITEA_HTTP_CLUSTER_IP=$(kubectl get -n default svc gitea-http -ojsonpath='{.spec.clusterIP}')
 - ip: 10.43.99.186
   hostnames:
     - gitea-127.0.0.1.sslip.io