#syntax=docker/dockerfile:1.3-labs

FROM python:3-alpine

LABEL org.opencontainers.image.source https://github.com/kameshsampath/dag-setup-verifier
LABEL org.opencontainers.image.authors="Kamesh Sampath<kamesh.sampath@hotmail.com>"

WORKDIR /usr/src/app

ARG TARGETARCH
ARG DRONE_TAG

COPY requirements.txt ./
RUN pip install -U pip  \
    && pip install --no-cache-dir -r requirements.txt

COPY app.py ./app.py

EXPOSE 8080

CMD [ "python","app.py" ]